version : '2'
services:

  springappserver:
    build:
      context: .
      dockerfile: springapp.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/vol/development
    links:
        - mongodb:mongodb

  mongodb:
    image: daocloud.io/library/mongo:latest
    ports:
      - "27017:27017"
