version : '2'
services:

  springappserver:
    image: registry.cn-hangzhou.aliyuncs.com/jimmy_miao/spring_boot_mongodb
#    build:
#      context: .
#      dockerfile: springapp.dockerfile
    command: "java -jar SpringBootMongoDocker-1.0-SNAPSHOT.jar"
    ports:
      - "8080:8080"
    volumes:
      - .:/vol/development
    links:
        - mongodb:mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
